# Generated by Django 4.1.3 on 2022-11-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='category_name',
        ),
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default=True, upload_to='categories'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default=True, upload_to='product'),
            preserve_default=False,
        ),
    ]
