# Generated by Django 4.1.3 on 2022-11-24 23:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_color_variant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryTo',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('country_name', models.CharField(max_length=120)),
                ('price', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='deli_country_name',
            field=models.ManyToManyField(null=True, to='products.deliveryto'),
        ),
    ]
